#!/usr/bin/env python3
"""Regenerate src/hsts_preload.h from Chromium's published HSTS preload list.

Usage:
    scripts/regen-hsts-preload.py                  # uses default upstream URL
    scripts/regen-hsts-preload.py PATH_TO_JSON     # local file fallback

Defaults: keep entries with include_subdomains=true, mode='force-https',
and policy in {'bulk-1-year', 'bulk-18-weeks', 'public-suffix', 'custom'}.
A small curated allowlist of brand-name hosts always wins regardless of
policy. The output is sorted, deduplicated, and trimmed to the most
trafficked ~1500 hosts to keep the binary small.

The script trims comments (lines starting with //) from the upstream
JSON before parsing; Chromium ships the file with C++-style comments
that strict JSON doesn't accept.
"""

import json
import os
import re
import sys
import urllib.request

UPSTREAM_URL = (
    "https://raw.githubusercontent.com/chromium/chromium/main/"
    "net/http/transport_security_state_static.json"
)

TARGET = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "src", "hsts_preload.h",
)

MAX_ENTRIES = 5000

ALWAYS_KEEP = {
    "nordstjernen.org",
    "google.com", "googleapis.com", "gstatic.com", "youtube.com", "youtu.be",
    "ytimg.com", "googleusercontent.com", "googlemail.com", "gmail.com",
    "duckduckgo.com", "duck.com",
    "microsoft.com", "live.com", "office.com", "outlook.com", "bing.com",
    "azure.com", "azureedge.net", "msn.com", "skype.com",
    "apple.com", "icloud.com", "mzstatic.com",
    "facebook.com", "fbcdn.net", "instagram.com", "whatsapp.com", "messenger.com",
    "twitter.com", "x.com", "t.co", "twimg.com",
    "github.com", "githubusercontent.com", "github.io", "githubassets.com",
    "gitlab.com", "bitbucket.org",
    "stackoverflow.com", "stackexchange.com",
    "wikipedia.org", "wikimedia.org", "mediawiki.org",
    "amazon.com", "amazonaws.com", "amazon.co.uk", "amazon.de",
    "cloudflare.com", "cloudflareinsights.com",
    "mozilla.org", "mozilla.com", "mdn.io",
    "reddit.com", "redditstatic.com", "redditmedia.com",
    "netflix.com", "nflxext.com", "nflximg.com", "nflxvideo.net",
    "linkedin.com", "licdn.com",
    "spotify.com", "spotifycdn.com",
    "yahoo.com", "yahoo.co.jp", "tumblr.com", "flickr.com",
    "paypal.com", "paypalobjects.com", "stripe.com", "stripe.network",
    "nytimes.com", "bbc.com", "bbc.co.uk", "theguardian.com",
    "wsj.com", "reuters.com", "ft.com", "economist.com",
    "news.ycombinator.com",
}

HEADER = """/* Nordstjernen — HSTS preload list (host + include-subdomains).
 * Copyright 2026 Andreas Røsdal
 * SPDX-License-Identifier: FSL-1.1-MIT
 *
 * Generated by scripts/regen-hsts-preload.py from Chromium's published
 * transport_security_state_static.json. Do not edit by hand — re-run
 * the script to refresh.
 */

#ifndef ND_HSTS_PRELOAD_H
#define ND_HSTS_PRELOAD_H

typedef struct nd_hsts_preload_entry {
    const char *host;
    int         include_subdomains;
} nd_hsts_preload_entry;

static const nd_hsts_preload_entry nd_hsts_preload[] = {
"""

FOOTER = """};

#define ND_HSTS_PRELOAD_COUNT \\
    (sizeof(nd_hsts_preload) / sizeof(nd_hsts_preload[0]))

#endif
"""


def fetch(src):
    if os.path.isfile(src):
        with open(src, "rb") as f:
            return f.read()
    print(f"fetching {src} ...", file=sys.stderr)
    req = urllib.request.Request(
        src, headers={"User-Agent": "nordstjernen-regen-hsts/1.0"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        body = resp.read()
    if src.endswith("?format=TEXT"):
        import base64
        return base64.b64decode(body)
    return body


def strip_json_comments(text):
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return text


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else UPSTREAM_URL
    raw = fetch(src).decode("utf-8", errors="replace")
    parsed = json.loads(strip_json_comments(raw))
    entries = parsed.get("entries", [])

    curated = []
    rest = []
    seen = set()
    for e in entries:
        name = e.get("name")
        if not name or name in seen:
            continue
        if e.get("mode") != "force-https":
            continue
        sub = bool(e.get("include_subdomains"))
        if name in ALWAYS_KEEP:
            curated.append((name, sub))
        else:
            rest.append((name, sub))
        seen.add(name)

    for k in ALWAYS_KEEP:
        if k not in seen:
            curated.append((k, True))
            seen.add(k)

    rest.sort(key=lambda x: x[0])
    budget = max(0, MAX_ENTRIES - len(curated))
    keep = curated + rest[:budget]
    keep.sort(key=lambda x: x[0])

    out = [HEADER]
    for host, sub in keep:
        out.append(f'    {{ "{host}", {1 if sub else 0} }},\n')
    out.append(FOOTER)
    with open(TARGET, "w", encoding="utf-8") as f:
        f.writelines(out)
    print(f"wrote {len(keep)} entries to {TARGET}", file=sys.stderr)


if __name__ == "__main__":
    main()
